import { GoogleGenAI } from '@google/genai';

// Lazy singleton — not initialized at module load time so build succeeds without env vars
let _genai: GoogleGenAI | null = null;
function getGenAI() {
  if (!_genai) {
    _genai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY! });
  }
  return _genai;
}

export interface GenerationResult {
  image: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

/**
 * Generate an image using native Gemini SDK.
 * @param prompt - Text prompt for image generation
 * @param inputImages - Array of base64 encoded images (person FIRST, then clothing)
 * @param aspectRatio - '1:1' | '2:3'
 */
export async function generateImageWithGemini(
  prompt: string,
  inputImages: string[],
  aspectRatioOption: '1:1' | '2:3' = '2:3'
): Promise<GenerationResult> {
  const model = 'gemini-2.5-flash-image';
  const response = await getGenAI().models.generateContent({
    model,
    contents: {
      parts: [
        ...inputImages.map(img => ({ inlineData: { mimeType: 'image/webp', data: img } })),
        { text: prompt },
      ],
    },
    config: {
      imageConfig: { aspectRatio: aspectRatioOption },
    },
  });

  const inputTokens = response.usageMetadata?.promptTokenCount || 0;
  const outputTokens = response.usageMetadata?.candidatesTokenCount || 0;
  const totalTokens = response.usageMetadata?.totalTokenCount || 0;

  let image: string | null = null;
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData?.data) {
      image = part.inlineData.data;
      break;
    }
  }

  if (!image) {
    throw new Error('No image generated by Gemini');
  }

  return { image, model, inputTokens, outputTokens, totalTokens };
}

export { AI_PROMPTS } from './ai-prompts';
